config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords }

  # devise_scope :user do
  #   authenticated :user do
  #     root 'threats#index', as: :authenticated_root
  #     # get 'devise/passwords#edit'
  #   end
  #
  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end
  root 'threats#index'

  namespace :admin do
    resources :threats
    resources :users do
      member do
        get :password
        patch :update_password
      end
      resource :profile, :controller => "user_profiles"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/threat.rb
class Threat < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

  validates :name, :presence => false, :uniqueness => true
  validates :age, numericality: { only_integer: true }
end

app/controllers/admin/threats_controller.rb
class Admin::ThreatsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy, :index]

  before_action :require_is_admin
  layout "admin"

  def show
    @threat = Threat.find(params[:id])
  end
  def index
    @threats = Threat.paginate(:page => params[:page], :per_page => 10)
  end
  def new
    @threat = Threat.new
  end
  def create
    @threat = Threat.new(threat_params)
    if @threat.save
      redirect_to admin_threats_path
    else
      render :new
    end
  end
  def edit
    @threat = Threat.find(params[:id])
  end
  def update
    @threat = Threat.find(params[:id])
    if @threat.update(threat_params)
      redirect_to admin_threats_path
    else
      render :edit
    end
  end
  def destroy
    @threat = Threat.find(params[:id])
    @threat.destroy
    redirect_to admin_threats_path
  end

  private

  def threat_params
    params.require(:threat).permit(:title, :description) end
end

app/controllers/admin/user_profiles_controller.rb
class Admin::UserProfilesController < ApplicationController
  before_action :find_user_and_profile

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  protected

  def find_user_and_profile
    @user = User.find(params[:user_id])
    # 因为新建的用户并没有 profile，所以这里先检查是否有 @user.profile，如果没有的话就用 @user.create_profile 新建进数据库
    @profile = @user.profile || @user.create_profile
  end

  def profile_params
    params.require(:profile).permit(:email, :name, :sex, :age, :position)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:alert] = "删除成功"
    redirect_to admin_users_path
  end

  def password
    @user = User.find(params[:id])
  end

  def update_password
    @user = User.find(params[:id])
    @user.reset_password_token = 'temp'
    @user.save!
    if @user.reset_password(params[:password], params[:password_confirmation])
      Notifier.admin_password_change(@user).deliver
      flash[:success] = "Password Changed ! "
      redirect_to update_password_admin_user_path(@user)
    else
      render "password"
      flash[:alert] = "Password Changed ? "
    end
  end

  protected

  def user_params
    params.require(:user).permit(:user, :email, :name, :sex, :age, :position, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    params.delete("email")
    params.delete("username")
    if params[:password].blank?
      params.delete(:current_password)
      params.delete(:password)
      params.delete(:password_confirmation)
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

    def after_update_path_for(resource)
      admin_users_path
    end

end

app/controllers/threats_controller.rb
class ThreatsController < ApplicationController
  before_action :authenticate_user! , only: [:new]
  def index
    @threats = Threat.paginate(:page => params[:page], :per_page => 10)
  end
  def show
    @threat = Threat.find(params[:id])
  end
  def new
    @threat = Threat.new
  end
  def edit
    @threat = Threat.find(params[:id])
  end
  def create
    @threat = Threat.new(threat_params)

    if @threat.save
      redirect_to threats_path
    else
      render :new
    end
  end
  def update
    @threat = Threat.find(params[:id])

    if @threat.update(threat_params)
      redirect_to threats_path, notice: "更新成功"
    else
      render :edit
    end
  end
  def destroy
    @threat = Threat.find(params[:id])
    @threat.destroy
    flash[:alert] = "删除成功"
    redirect_to threats_path
  end

  private
    def threat_params
      params.require(:threat).permit(:title, :description)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show

  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render "edit"
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :name)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/threats_helper.rb
module Admin::ThreatsHelper
end

app/helpers/admin/user_profiles_helper.rb
module Admin::UserProfilesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/threats_helper.rb
module ThreatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/threats/edit.html.erb
<h1> Edit a threat </h1>
<%= simple_form_for [:admin, @threat ] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/admin/threats/index.html.erb
<div class="pull-right">
  <%= link_to("新增情报", new_admin_threat_path, :class => "btn btn-default" ) %>
</div>
<br>
<br>
<table class="table">
  <tr>
    <th>标题</th>
    <th>详情</th>
    <th>更新时间</th>
    <th>操作</th>
  </tr>
  <% @threats.each do |threat| %>
    <tr>
      <td>
        <%= link_to(threat.title, admin_threat_path(threat)) %>
      </td>
      <td>
        <%= link_to(threat.description, admin_threat_path(threat)) %>
      </td>
      <td>
        <%= threat.created_at %>
      </td>
      <td>
        <%= link_to("Edit", edit_admin_threat_path(threat)) %>
        <%= link_to("Destroy", admin_threat_path(threat), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
      </td>

    </tr>
  <% end %>
</table>
<%= will_paginate @threats %>

app/views/admin/threats/new.html.erb
<h1> Add a threat </h1>
<%= simple_form_for [:admin,@threat] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit "Submit" %>
<% end %>

app/views/admin/threats/show.html.erb
<h1> <%= @threat.title %> </h1>
<p> <%= simple_format(@threat.description) %></p>

app/views/admin/user_profiles/edit.html.erb
<h1>Edit User Profile</h1>

<div class="userform">
  <%= form_for @profile, :url => admin_user_profile_path(@user) do |f| %>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :sex %>
      <select class="form-control" id="FormControlSelect1">
        <option>男</option>
        <option>女</option>
      </select>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.text_field :age, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :position %>
      <%= f.text_field :position, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @user] do |f| %>

<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :sex %>
  <%= f.select :sex, [["男"],["女"]] %>
</div>
<div class="form-group">
  <%= f.label :age %>
  <%= f.text_field :age, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :position %>
  <%= f.text_field :position, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.submit "Update", :class => "btn btn-primary" %>
  <%= link_to "Cancel", admin_users_path %>
</div>

<% end %>

app/views/admin/users/index.html.erb
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增用户", new_admin_user_path, class: "btn btn-primary btn-sm") %>
</div>


<table class="table">
<tr>
  <th>序号</th>
  <th>邮箱</th>
  <th>姓名</th>
  <th>性别</th>
  <th>年龄</th>
  <th>职位</th>
  <th>操作</th>
</tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= user.sex %></td>
    <td><%= user.age %></td>
    <td><%= user.position %></td>
    <td><%= link_to "编辑资料", edit_admin_user_path(user), :class => "btn btn-default" %></td>
    <td><%= link_to "修改密码", password_admin_user_path(user), :class => "btn btn-default" %></td>
    <td><%= link_to "删除用户", admin_user_path(user), :class => "btn btn-default", :method => :delete, :data => { :confirm => "Are you sure?"  } %></td>

  </tr>
<% end %>
</table>

<%= will_paginate @users %>

app/views/admin/users/new.html.erb
<h1>新增用户</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @user] do |f| %>

<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :sex %>
  <%= f.select :sex, [["男"],["女"]] %>
</div>
<div class="form-group">
  <%= f.label :age %>
  <%= f.text_field :age, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :position %>
  <%= f.text_field :position, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.submit "Update", :class => "btn btn-primary" %>
  <%= link_to "Cancel", admin_users_path %>
</div>

<% end %>

app/views/admin/users/password.html.erb
<h1>Edit User</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @user], url: {action: "update_password"}, html: {method: "patch"} do |f| %>

<div class="form-group">
  <%= f.label :email %>
  <%= @user.email %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :confirmation_password %>
  <%= f.password_field :confirmation_password, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.submit "Update", :class => "btn btn-primary" %>
  <%= link_to "Cancel", admin_users_path %>
</div>

<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <div class="col-md-12">
    Designed by Bingo8670
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">NOSEC</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %> </li>
          <li><%= link_to("登录", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
              <li><%= link_to("用户管理", admin_users_path)%></li>
                <li><%= link_to("情报管理", admin_threats_path)%></li>
              <% end %>
              <li><%= link_to "修改密码", edit_registration_path(current_user) %></li>
              <li class="divider"> </li>
              <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>


            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NOSEC
    </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
            <li class="active">
              <%= link_to("用户管理", admin_users_path ) %>
              <%= link_to("情报管理", admin_threats_path ) %>
            </li>
          </ul>
        </div>
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bmh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
       <%= render "common/navbar" %>
       <%= render "common/flashes" %>
      <%= yield %>
    </div>
      <%= render "common/footer" %>
  </body>
</html>

app/views/threats/_form.html.erb
<%= form_for @threat do |f| %>
  <% if @threat.errors.any? %>
    <ul>
      <% @threat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  标题 <%= f.text_field :title %> <br>
  叙述 <br> <%= f.text_area :description %> <br>
  <%= f.submit "Submit", :disable_with => 'Submitting...' %>
<% end %>

app/views/threats/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>编辑威胁情报</h1>
  <hr>
  <%= render "form" %>
</div>

app/views/threats/index.html.erb
<div class="col-md-12">
  <div class="threat">
    <%= link_to("New threat", new_admin_threat_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody> <% @threats.each do |threat| %>
      <tr>
        <td>#</td>
        <td><%= link_to(threat.title, admin_threat_path(threat)) %></td>
        <td><%= threat.description %></td>
        <td> <%= link_to("Edit", edit_admin_threat_path(threat), class: "btn btn-sm btn-primary")%>
        <%= link_to("Delete", admin_threat_path(threat), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "Are you sure?" } )%> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @threats %>
</div>

app/views/threats/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增威胁情报</h1>
  <hr>
  <%= render "form" %>
</div>

app/views/users/index.html.erb
<td>
  <%= link_to "Edit", edit_admin_user_path(user), :class => "btn btn-default" %>
</td>
<td>
  <%= link_to "Edit Profile", edit_admin_user_profile_path(user), :class => "btn btn-default" %>
</td>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= link_to "current_user_show", current_user %>